import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'dart:io';
import '../../services/TradeService.dart';
import '../../models/TradeModels.dart';

class MakeTradePage extends StatefulWidget {
  @override
  _MakeTradePageState createState() => _MakeTradePageState();
}

class _MakeTradePageState extends State<MakeTradePage> {
  final TradeService _tradeService = TradeService();
  File? _image;
  final picker = ImagePicker();

  final _nameController = TextEditingController();
  final _quantityController = TextEditingController();
  final _descController = TextEditingController(); // <--- Added controller
  final _prefController = TextEditingController();

  List<String> _preferredTrades = [];
  bool _isLoading = false;

  Future<void> _pickImage() async {
    final pickedFile = await picker.pickImage(source: ImageSource.gallery);
    if (pickedFile != null) setState(() => _image = File(pickedFile.path));
  }

  void _addPref() {
    if (_prefController.text.isNotEmpty) {
      setState(() {
        _preferredTrades.add(_prefController.text.trim());
        _prefController.clear();
      });
    }
  }

  Future<void> _submit() async {
    if (_nameController.text.isEmpty || _quantityController.text.isEmpty) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Fill in required fields')));
      return;
    }

    setState(() => _isLoading = true);

    try {
      final newListing = TradeListing(
        id: '', // Generated by Firestore
        name: _nameController.text,
        quantity: _quantityController.text,
        description: _descController.text, // <--- Included in submission
        preferredTrades: _preferredTrades,
        image: _image?.path ?? '',
        userId: '', // Service handles this
        offersCount: 0,
        createdAt: DateTime.now(),
      );

      await _tradeService.createListing(newListing);

      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Trade Posted!')));
      Navigator.pop(context);
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Error: $e')));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Make a Trade", style: TextStyle(color: Colors.black)),
        backgroundColor: Colors.white,
        elevation: 0,
        iconTheme: IconThemeData(color: Colors.black),
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            TextField(
              controller: _nameController,
              decoration: InputDecoration(
                labelText: 'Item Name',
                border: OutlineInputBorder(),
              ),
            ),
            SizedBox(height: 12),
            TextField(
              controller: _quantityController,
              decoration: InputDecoration(
                labelText: 'Quantity',
                border: OutlineInputBorder(),
              ),
            ),
            SizedBox(height: 12),

            // --- NEW DESCRIPTION FIELD ---
            TextField(
              controller: _descController,
              maxLines: 3, // Allows multiple lines for details
              decoration: InputDecoration(
                labelText: 'Product Details / Description',
                alignLabelWithHint: true,
                border: OutlineInputBorder(),
              ),
            ),
            SizedBox(height: 12),

            // -----------------------------
            GestureDetector(
              onTap: _pickImage,
              child: Container(
                height: 120,
                width: double.infinity,
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.grey),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: _image == null
                    ? Icon(Icons.add_a_photo)
                    : Image.file(_image!, fit: BoxFit.cover),
              ),
            ),
            SizedBox(height: 16),
            Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _prefController,
                    decoration: InputDecoration(
                      hintText: 'Add preferred item',
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
                IconButton(
                  icon: Icon(Icons.add_circle, color: Colors.green),
                  onPressed: _addPref,
                ),
              ],
            ),
            Wrap(
              spacing: 8,
              children: _preferredTrades
                  .map(
                    (t) => Chip(
                      label: Text(t),
                      onDeleted: () =>
                          setState(() => _preferredTrades.remove(t)),
                    ),
                  )
                  .toList(),
            ),
            SizedBox(height: 24),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: _isLoading ? null : _submit,
                child: _isLoading
                    ? CircularProgressIndicator()
                    : Text('Post Trade'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Color(0xFFC3E956),
                  foregroundColor: Colors.black,
                  padding: EdgeInsets.all(16),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
